name: nextai
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.6
  - numpy
  - scipy
  - pandas
  - matplotlib
  - jupyter
  - nbstripout
  - seaborn
  - scikit-learn
  - scikit-optimize
  - tqdm
  - future
  - pytorch
  - torchvision
